spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost/mydb?currentSchema=core
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: core
      password: APP
    
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

server:
  port: 8081
  
  
# 允许生成代码的 schema 集合
allowSchema: mstdata,bommgmt,chgmgmt,cfgmgmt,integration,cust